### ISSUE TITLE
Proposta de padronização de schema URN para pagamentos

### ISSUE THREAD

**Issue by jayderfranca** [niobio-cash/ncip#10]
Gostaria de fazer uma proposta de padronização de schema URN para pagamentos em Niobio Cash.

Inspirado na [Bitcoin - BIP 21](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) a definição seria:

Sintaxe:
* [] dados opcionais
* <> dados a serem substituidos

``
niobiocash:<address>[?amount=<amount>][&label=<label>][&payid=<payid][&anon=<anon>][&desc=<description>]
``

Sendo:
address: Endereço de destino
amount: Valor total de transferência (Sem a taxa)
label: Uma identificação do destino
anon:  Nível de anonimato
desc: Descrição desta transferência

O amount, poderá ser o valor inteiro, sendo que a moeda já possui a definição de 8 casa, exemplos: 
* 100000000, identifica o valor de 1 NBR
* 10000000, identifica o valor de 0.1 NBR

Após esta discussão podemos criar uma NCIP com a definição e todo processo de pagamento automatizado poderá adotar esta padronização.

Onde aplicar esta padronização ?
* QR codes
* Sites que desejam capturar o preenchimento automático de transferências
* Etc

Este é somente um esborço e inicio de debates.

Definição de URN: https://www.ietf.org/rfc/rfc3986.txt

**Comment by helder-garcia** [comment]
NCIP created https://github.com/niobio-cash/ncip/blob/master/ncip-0008.mediawiki
